"""initial schema

Revision ID: 337e37826129
Revises: 
Create Date: 2026-04-01 22:39:24.866580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337e37826129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_class', sa.String(length=100), nullable=False),
    sa.Column('booking_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photographer_name', sa.String(length=200), nullable=False),
    sa.Column('page_title', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('about_image', sa.String(length=500), nullable=False),
    sa.Column('hero_image_1', sa.String(length=500), nullable=False),
    sa.Column('hero_image_2', sa.String(length=500), nullable=False),
    sa.Column('vk_url', sa.String(length=500), nullable=False),
    sa.Column('telegram_url', sa.String(length=500), nullable=False),
    sa.Column('instagram_url', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('email_public', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('counter_equipment', sa.Integer(), nullable=False),
    sa.Column('counter_studio', sa.Integer(), nullable=False),
    sa.Column('counter_sessions', sa.Integer(), nullable=False),
    sa.Column('counter_clients', sa.Integer(), nullable=False),
    sa.Column('instagram_section_title', sa.String(length=200), nullable=False),
    sa.Column('public_short_name', sa.String(length=200), nullable=False),
    sa.Column('hero_subtitle', sa.String(length=500), nullable=False),
    sa.Column('author_image_paths', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.drop_table('service_items')
    op.drop_table('feedback_messages')
    op.drop_table('collection_items')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
